name: csv-tool
channels:
  - conda-forge
  - defaults
dependencies:
  - chardet
  - python-multipart
  - python-dotenv
  - python=3.10
  - fastapi>=0.68.0,<0.69.0
  - pydantic>=1.8.0,<2.0.0
  - uvicorn>=0.15.0,<0.16.0
  - pip
#  - pip: 
#    - foo
